apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: logs
spec:
  version: 3.9.0
  replicas: 1
  connectCluster: "target"
  clusters:
    - alias: source
      bootstrapServers: 104.248.25.198:32302
    - alias: target
      bootstrapServers: logs-kafka-bootstrap.kafka.svc:9092
  mirrors:
    - sourceCluster: source
      targetCluster: target
      sourceConnector:
        config:
          replication.factor: 1
          offset-syncs.topic.replication.factor: 1
          offset.storage.replication.factor: 1
          config.storage.replication.factor: 1
          status.storage.replication.factor: 1
          replication.policy.class: "org.apache.kafka.connect.mirror.IdentityReplicationPolicy"
      heartbeatConnector:
        config:
          heartbeats.topic.replication.factor: 1
      checkpointConnector:
        config:
          checkpoints.topic.replication.factor: 1
      topicsPattern: "logs|logs-cez2"
      groupsPattern: ".*"
