apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.0.13
    helm:
      releaseName: ingress-nginx
      # https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
      valuesObject:
        controller:
          service:
            type: ClusterIP
          ingressClassResource:
            default: true
          kind: DaemonSet
          hostPort:
            enabled: true
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
        defaultBackend:
          enabled: true
          image:
            registry: docker.io
            image: sikalabs/sikalabs-kubernetes-ingress-default-page
            tag: latest
            pullPolicy: Always
          extraEnvs:
            - name: CLUSTER
              value: "cez3"
            - name: DOMAIN
              value: "k8s3.sikademo.com"
          port: 8000
