configs:
  cm:
    url: https://argocd.k8s.sikademo.com
    oidc.config: |
      name: SSO
      issuer: https://sso.sikalabs.com/realms/sikademo
      clientID: argocd
      clientSecret: argocd
      requestedScopes: ["openid", "profile", "email", "groups"]
      logoutURL: "https://sso.sikalabs.com/realms/sikademo/protocol/openid-connect/logout?client_id=argocd&id_token_hint={{token}}&post_logout_redirect_uri=https://argocd.k8s.sikademo.com"
  rbac:
    scopes: '[groups]'
    policy.default: ""
    policy.csv: |
      g, argocd-admin, role:admin
      g, argocd-readonly, role:readonly
server:
  ingress:
    enabled: true
    hostname: argocd.k8s.sikademo.com
    tls: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
