apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-cez
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: hello-cez
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    path: charts/hello-world
    helm:
      valuesObject:
        host: cez3.sikademo.com
        image: ghcr.io/sikalabs/hello-world-server:cez
        replicas: 4
