apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk-ondrej
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: elk-ondrej
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://gitlab.sikademo.com/examples/cez/argocd-apps-cez-example.git
    path: apps/cez/elk_ondrej/manifests
