grafana:
  enabled: true
  assertNoLeakedSecrets: false
  defaultDashboardsEnabled: false
  serviceMonitor:
    selfMonitor: false
  adminPassword: "admin"
  sidecar:
    datasources:
      enabled: true
    dashboards:
      enabled: true
  additionalDataSources:
    - name: loki
      orgId: 1
      uid: loki
      url: http://loki-gateway.logging
      access: proxy
      isEnabled: true
      type: loki

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - grafana.cez3.sikademo.com
    tls:
      - hosts:
          - grafana.cez3.sikademo.com
        secretName: grafana.cez3.sikademo.com-tls

  grafana.ini:
    server:
      root_url: https://grafana.cez3.sikademo.com
    users:
      viewers_can_edit: true
    auth.basic:
      enabled: true
    auth:
      disable_login_form: false
    auth.generic_oauth:
      enabled: true
      name: CEZ SSO
      scopes: "openid profile email"
      allow_sign_up: true
      api_url: https://sso.sikalabs.com/realms/sikademo/protocol/openid-connect/userinfo
      auth_url: https://sso.sikalabs.com/realms/sikademo/protocol/openid-connect/auth
      token_url: https://sso.sikalabs.com/realms/sikademo/protocol/openid-connect/token
      client_id: default
      client_secret: default
      role_attribute_path: >
        'Admin'
    smtp:
      enabled: false

alertmanager:
  enabled: false

prometheus:
  enabled: false

kubeScheduler:
  enabled: false

kubeControllerManager:
  enabled: false

kubeProxy:
  enabled: false

kubeEtcd:
  enabled: false

defaultRules:
  enabled: false
