apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: logging
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.25.0
      helm:
        releaseName: loki
        valueFiles:
          - $values/apps/cez3/loki/values.yaml
    - repoURL: https://gitlab.sikademo.com/examples/cez/argocd-apps-cez-example.git
      targetRevision: HEAD
      ref: values
